# Configuration of Hugo
# Guide: https://wowchemy.com/docs/getting-started/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

title: Pinaki Bhattacharyya
baseurl: https://pbhattacharyya.rbind.io
copyright: 'Copyright &copy;{year} Pinaki Bhattacharyya, All right reserved'
theme: hugo-academic

############################
## LANGUAGE
############################

defaultContentLanguage: en
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true

############################
## MODULES
############################

module:
  imports:
    - path: github.com/wowchemy/wowchemy-hugo-modules/wowchemy-cms
    - path: github.com/wowchemy/wowchemy-hugo-modules/wowchemy
    
############################
## ADVANCED
############################

enableGitInfo: false
summaryLength: 30
paginate: 10
enableEmoji: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles:
  - \.ipynb$
  - .ipynb_checkpoints$
  - \.Rmd$
  - \.Rmarkdown$
  - \.knit\.md$
  - \.utf8\.md$
  - _cache$
permalinks:
  event: '/talk/:slug/'
  tags: '/tag/:slug/'
  categories: '/category/:slug/'
  publication_types: '/publication-type/:slug/'
disableAliases: true
outputs:
  home:
    - HTML
    - RSS
    - JSON
    - WebAppManifest
    - headers
    - redirects
  section:
    - HTML
    - RSS
mediaTypes:
  application/manifest+json:
    suffixes: webmanifest
outputFormats:
  WebAppManifest:
    mediaType: application/manifest+json
    rel: manifest
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
  highlight:
    codeFences: true
    style: pygments
  tableOfContents:
    startLevel: 2
    endLevel: 4
imaging:
  anchor: smart
  quality: 75
  resampleFilter: lanczos
timeout: 600000
taxonomies:
  author: authors
  category: categories
  publication_type: publication_types
  tag: tags
related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 70

